import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button, NoSsr, ThemeProvider } from "@mui/material";
import BasicButtons from "@/components/Button/Button";
import Navbar from "@/components/Navbar/Navbar";
import theme from "./theme";
import Routing from "./routing";
import createEmotionCache from "@/utils/createEmotionCache";
import { CacheProvider } from "@emotion/react";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-basicWhite`}
      >
        <Routing children={children} />
      </body>
    </html>
  );
}
